import type { Metadata } from "next";
import "./globals.css";
import Header from "./Compontents/Header/header";
import Footer from "./Compontents/Footer/footer";



export const metadata: Metadata = {
  title: "Project-cv",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script defer src="https://kit.fontawesome.com/41c8b474e2.js" crossOrigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/686402c9d7.js" crossOrigin="anonymous"></script>
      </head>
      <body>
        <div className="wrapper">
          <Header/>
          {children}
          <Footer/>
        </div>
      </body>
      
    </html>
  );
}
